### ISSUE TITLE
micropub_media not picked up correctly

### ISSUE THREAD

**Issue by ngm** [jgarber623/indieweb-endpoints.cc#10]
See e.g.: https://indieweb-endpoints.cc/search?url=https%3A%2F%2Fdoubleloop.net

[micropub_media](https://indieweb.org/micropub_media_endpoint) is missing, and micropub is reported as the media endpoint.

![image](https://user-images.githubusercontent.com/172324/58290269-136b6700-7db1-11e9-9fcb-09be47401a0e.png)

The actual values are:
```
<link rel="micropub_media" href="https://doubleloop.net/wp-json/micropub/1.0/media" />
<link rel="micropub" href="https://doubleloop.net/wp-json/micropub/1.0/endpoint" />
```

**Comment by ngm** [comment]
As per [chat](https://chat.indieweb.org/dev/2019-05-23#t1558650001022500), micropub_media is experimental, so perhaps optional as to whether it is reported.  But it's also causing the actual micropub endpoint to have the wrong value.

**Comment by jgarber623** [comment]
Great catch, @ngm. Thanks for filing this issue.

This is a problem in the upstream dependency [indieweb-endpoints-ruby](https://github.com/indieweb/indieweb-endpoints-ruby) gem. I'll keep this issue open and address the underlying problem over there.

**Comment by jgarber623** [comment]
@ngm Resolved and deployed! https://indieweb-endpoints.cc/search?url=https%3A%2F%2Fdoubleloop.net
